name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    env:
      NAME: '${{ secrets.DOCKERHUB_USERNAME }}/flexget'
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Generate tags
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["${{ env.NAME }}:latest","${{ env.NAME }}:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["${{ env.NAME }}:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        needs: gen_tags
        with:
          context: .
          push: true
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
